# Generated by Django 4.2.2 on 2023-06-09 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_answer_question_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='listings.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
