# Generated by Django 4.2.2 on 2023-06-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_question_choice_question_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
