# Generated by Django 4.2.2 on 2023-06-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_quiz_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
