# Generated by Django 4.2.2 on 2023-06-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_question_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/quiz/'),
        ),
    ]
